BATCH_SIZE = 20
FEATURE_DIM_1 = 288
FEATURE_DIM_2 = 384
NUM_CHANNEL = 3
NUM_LABEL = 2
EPOCHS = 50
VERBOSE = 1
MODEL_NAME = 'toy_model'
DATA_PATH = '/Users/kyloris/Downloads/HeadPoseImageDatabase/photo/'
SAVE_NAME = 'model_' + str(EPOCHS) + 'epochs_' + MODEL_NAME + '.h5'